apiVersion: v1
kind: Service
metadata:
  name: bluegreen-demo
  labels:
    app: bluegreen-demo
spec:
  ports:
  - port: 9898
    targetPort: http
    protocol: TCP
    name: http
    nodePort: 30401
  type: NodePort
  selector:
    app: bluegreen-demo
