apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bluegreen
  name: bluegreen-svc
spec:
  ports:
  - port: 9876
    protocol: TCP
    targetPort: 8080
  selector:
    app: bluegreen
  type: NodePort
status:
  loadBalancer: {}
