apiVersion: v1
kind: Service
metadata:
  name: canary-demo-preview
  labels:
    app: canary-demo
spec:
  ports:
  - port: 9797
    targetPort: http
    protocol: TCP
    name: http
    nodePort: 30202
  type: NodePort

  selector:
    app: canary-demo
